// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtcvexdklcxcyqywhnva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0Y3ZleGRrbGN4Y3lxeXdobnZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDQ5MjUsImV4cCI6MjA3MTg4MDkyNX0.2Gf-ydVAjVkxFRi_zAWl0scEXCjxrsujU015c3jrCG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});